# Uncomment this line to define a global platform for your project
# platform :ios, ’9.0’
use_frameworks!
def development_pods
  pod ‘Utility’, :git => 'https://github.com/murali-git/Utility.git’
end
 
target ‘LoginWorkingExample’ do
    development_pods
end